In [2]:
import numpy as np
import cv2

Gray_One = cv2.imread("Bangla_1.jpg",0)
cv2.imshow("one",Gray_One)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_array = np.array(Gray_One)
print("Image Shape:", image_array.shape)

Image Shape: (240, 177)


In [3]:
resized_One = cv2.resize(Gray_One, (18, 20))
cv2.imshow("Bangla One",resized_One)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_Matrix1 = np.array(resized_One)
print(image_Matrix1)

[[255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 253   1   0 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255   1 137 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255  55   0 199 254 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255   0   3 254 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 253   1 255 255 255 255 255 255]
 [255 255 255 255 255 255 254   0   0 255 255   2 255 255 255 255 255 255]
 [255 255 255 255 255 255 254   0 218 255   2 255 255 255 255 255 255 255]
 [255 255 255 255 255 255

In [ ]:
import cv2
import numpy as np

One_Bangla = np.array([
    [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 253, 0,   0,   255, 255, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 0,   137, 255, 255, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 55,  0,   199, 254, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 255, 255, 0,   0,   254, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 253, 1,   255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 254, 0,   0,   255, 255, 0,   255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 254, 0,   0,   0,   0,   0, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 255, 242, 240, 254, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
    [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
])
#inverted_digit = 255 - One_Bangla
bengali_digit_image = np.uint8(One_Bangla * 255)
One_BanglaR = cv2.resize(bengali_digit_image, (500, 500), interpolation=cv2.INTER_NEAREST)
cv2.imshow('One_Bangla', One_BanglaR)
cv2.waitKey(0)
cv2.destroyAllWindows()

