In [1]:
import numpy as np
import cv2

Gray_Zero = cv2.imread("Bangla_0.png",0)
cv2.imshow("Zero",Gray_Zero)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_array = np.array(Gray_Zero)
print("Image Shape:", image_array.shape)

Image Shape: (155, 115)


In [2]:
resized_Zero = cv2.resize(Gray_Zero, (18, 20))
cv2.imshow("Bangla Zero",resized_Zero)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_Matrix0 = np.array(resized_Zero)
print(image_Matrix0)

[[255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 254 255 255 255 255 254 255 255 255 255 255]
 [255 255 255 255 254 249 245  19   4   4   9 245 249 253 255 255 255 255]
 [255 255 255 255 244   1   1   2   1   0   5   5   3 245 255 255 255 255]
 [255 255 253 252   5   1   5 110 242 254 254 251  50   3 252 255 255 255]
 [255 255 254   3   0   3 247 255 255 255 255 254 252   6   7 253 255 255]
 [255 255 253   2   2 198 255 255 255 255 255 255 252   2   2 253 255 255]
 [255 255 251   3   3 252 255 255 255 255 255 254 251   1   0 255 255 255]
 [252 255 252   1   1 253 255 255 255 255 254 250  98   4   5 254 255 255]
 [253 254 253  13   4 247 255 255 254 254 253 136   1   4  11 254 255 255]
 [255 255 255 250   6   8