In [1]:
import numpy as np
import cv2

Gray_Four = cv2.imread("Bangla_4.png",0)
cv2.imshow("one",Gray_Four)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_array = np.array(Gray_Four)
print("Image Shape:", image_array.shape)

Image Shape: (173, 263)


In [3]:
resized_Four = cv2.resize(Gray_Four, (18, 20))
cv2.imshow("Bangla One",resized_Four)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_Matrix4 = np.array(resized_Four)
print(image_Matrix4)

[[255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 253 251 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 240   7   3   4 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 252   6 254 252   7 253 255 255 255 255 255 255]
 [255 255 255 255 255 255 253   1 255 255 253 254 255 255 255 255 255 255]
 [255 255 255 255 255 255 253   0 253 253   4 254 255 255 255 255 255 255]
 [255 255 255 255 255 255 254   5 224 252   9 254 255 255 255 255 255 255]
 [255 255 255 255 255 255 255  17   1   3 251 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 244   3   4   2 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 250   9 245 253   1 171 255 255 255 255 255 255]
 [255 255 255 255 255 255 229   3 255 255 135   1 255 255 255 255 255 255]
 [255 255 255 255 255 255 169  14 255 255 249   4 255 255 255 255 255 255]
 [255 255 255 255 255 255