In [1]:
import numpy as np
import cv2

Gray_Eight = cv2.imread("Bangla_8.png",0)
cv2.imshow("Two",Gray_Eight)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_array = np.array(Gray_Eight)
print("Image Shape:", image_array.shape)

Image Shape: (176, 216)


In [2]:
resized_Eight = cv2.resize(Gray_Eight, (18, 20))
cv2.imshow("Bangla Eight",resized_Eight)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_Matrix8 = np.array(resized_Eight)
print(image_Matrix8)

[[254 254 254 254 254 254 254 254 254 254 254 254 254 254 254 254 254 254]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255   2 233 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255   6   2 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 178   3 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255   3 253 255 255 255 255 252 255 255 255 255 255]
 [255 255 255 255 255 253   4 134   1 246 253   2   8 254 255 255 255 255]
 [255 255 255 255 255 253   3   1   5   2   6   1   8 255 255 255 255 255]
 [255 255 255 255 255 253   4 255 255  50 143 253 254 255 255 255 255 255]
 [255 255 255 255 255 253   3 255 255  58   6 255 255 255 255 255 255 255]
 [255 255 255 255 255 254   3 255 255   9   3 255 255 255 255 255 255 255]
 [255 255 255 255 255 253