In [1]:
import numpy as np
import cv2

Gray_Two = cv2.imread("Bangla_2.png",0)
cv2.imshow("Two",Gray_Two)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_array = np.array(Gray_Two)
print("Image Shape:", image_array.shape)

Image Shape: (173, 237)


In [4]:
resized_Two = cv2.resize(Gray_Two, (18, 20))
cv2.imshow("Bangla Two",resized_Two)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_Matrix2 = np.array(resized_Two)
print(image_Matrix2)

[[255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 126 254 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255   3 112 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255   4   4 166 253 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 251   4   4 249 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 254   7   7 255 255 255 255 255 255 255]
 [255 255 255 255 255 254 255 255 255 255  10 255 255 255 255 255 255 255]
 [255 255 255 255 255 248 241 255 255 255 196 254 255 255 255 255 255 255]
 [255 255 255 255 255 250   2 255 254 253  21 254 255 255 255 255 255 255]
 [255 255 255 255 255 254   4   3  25   6  10 254 255 255 255 255 255 255]
 [255 255 255 255 255 255