In [1]:
import numpy as np
import cv2

Gray_Three = cv2.imread("Bangla_3.png",0)
cv2.imshow("Three",Gray_Three)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_array = np.array(Gray_Three)
print("Image Shape:", image_array.shape)

Image Shape: (176, 278)


In [2]:
resized_Three = cv2.resize(Gray_Three, (18, 20))
cv2.imshow("Bangla_Three",resized_Three)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_Matrix3 = np.array(resized_Three)
print(image_Matrix3)

[[254 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 255 255 253 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 254 134   6 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 251 255 254   2   2   7 255 255 255 255 255 255 255]
 [254 255 255 255 255 254 254 249   2   4  10 252 255 255 255 255 255 255]
 [254 255 255 255 255 254 252 252   2   2 248  78 255 255 255 255 255 255]
 [254 255 255 255 255 255 220 251   2   5 255   6 255 255 255 255 255 255]
 [254 255 255 255 255 255   3 255 237 245 255   6 255 255 255 255 255 255]
 [254 255 255 255 255 255   8 255 255 255 255   4 255 255 255 255 255 255]
 [254 255 255 255 255 255  94 245 255 255 254   3 255 255 255 255 255 255]
 [254 255 255 255 255 255