In [1]:
import numpy as np
import cv2

Gray_Nine = cv2.imread("Bangla_9.png",0)
cv2.imshow("Nine",Gray_Nine)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_array = np.array(Gray_Nine)
print("Image Shape:", image_array.shape)

Image Shape: (170, 263)


In [2]:
resized_Nine = cv2.resize(Gray_Nine, (18, 20))
cv2.imshow("Bangla Nine",resized_Nine)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_Matrix9 = np.array(resized_Nine)
print(image_Matrix9)

[[254 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 244  16 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255   9   4 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255  84  21 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 245   3  43 254 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 254  74   2   9 254 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 253  96   1   6 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 252 251   2 236 255 255 255 255 255 255]
 [255 255 255 255 255 255 255   4   3 241 237   1 255 255 255 255 255 255]
 [255 255 255 255 255 254 246   9 248  13 255   4 255 255 255 255 255 255]
 [255 255 255 255 255 255   3 255 254   5 255   2 255 255 255 255 255 255]
 [255 255 255 255 255 255