In [3]:
import numpy as np
import cv2

Gray_Seven = cv2.imread("Bangla_7.png",0)
cv2.imshow("Seven",Gray_Seven)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_array = np.array(Gray_Seven)
print("Image Shape:", image_array.shape)

Image Shape: (174, 284)


In [4]:
resized_Seven = cv2.resize(Gray_Seven, (18, 20))
cv2.imshow("Bangla Seven",resized_Seven)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_Matrix7 = np.array(resized_Seven)
print(image_Matrix7)

[[254 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 255 254 254 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255   3   5   8 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 245   3 252   1 254 255 255 255 255 255 255 255]
 [254 255 255 255 255 255  18 248 255 193 253 255 255 255 255 255 255 255]
 [254 255 255 255 255 255   1 253 255 254 244 255 255 255 255 255 255 255]
 [254 255 255 255 255 255   1 243 255 253  57 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 254   3   1   1  16 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 232 173 169   8 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 255 255 254  17 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 255 255 254  23 255 255 255 255 255 255 255]
 [254 255 255 255 255 255