In [1]:
import numpy as np
import cv2

Gray_Five = cv2.imread("Bangla_5.png",0)
cv2.imshow("Five",Gray_Five)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_array = np.array(Gray_Five)
print("Image Shape:", image_array.shape)

Image Shape: (174, 270)


In [2]:
resized_Five = cv2.resize(Gray_Five, (18, 20))
cv2.imshow("Bangla Five",resized_Five)
cv2.waitKey(0)
cv2.destroyAllWindows()

image_Matrix5 = np.array(resized_Five)
print(image_Matrix5)

[[254 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 255 255 250 254 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 254 131   2  63 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255 254   3   7 253 255 255 255 255 255 255 255]
 [254 255 255 255 255 255 255   1  15 253  43 253 255 255 255 255 255 255]
 [254 255 255 255 255 255 254  14 251 255   1   5 252 255 255 255 255 255]
 [254 255 255 255 255 255 253  10 255 255   4   9 252 255 255 255 255 255]
 [254 255 255 255 255 255  14 254 255 171   2 255 255 255 255 255 255 255]
 [254 255 255 255 255 255   1 255 255   0 251 255 255 255 255 255 255 255]
 [254 255 255 255 255 255   1 255 255   2 254 255 255 255 255 255 255 255]
 [254 255 255 255 255 255  31 255 255   2 255 255 255 255 255 255 255 255]
 [254 255 255 255 255 255